apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: dca-phpinfo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dca-phpinfo
  template:
    metadata:
      labels:
        app: dca-phpinfo
        otra: xxx
    spec:
      containers:
        -
          image: kikof/dca-phpinfo:latest
          name: dca-phpinfo
          ports:
            - containerPort: 8080
